#!/bin/bash
#BSUB -n 1
#BSUB -gpu "num=1:mode=shared:j_exclusive=yes"
#BSUB -R "rusage[mem=2]"
#BSUB -q short
#BSUB -o /gpfs/scratch/bz957/brats/skynet_scripts/post_3cases_%J.log


. /gpfs/share/skynet/apps/anaconda3/etc/profile.d/conda.sh
conda activate /gpfs/scratch/bz957/brats_skynet
###conda activate powerai1.6_env
cd /gpfs/scratch/bz957/brats

python -u test_batches.py config17/test_all_class.txt /gpfs/scratch/bz957/brats/data/langone/post/post_3cases
