#!/bin/bash
#BSUB -n 1
#BSUB -gpu "num=1:mode=shared:j_exclusive=yes"
#BSUB -R "rusage[mem=2]"
#BSUB -q short
#BSUB -o /gpfs/scratch/bz957/skull_stripping/skynet_scripts/test_%J.log


. /gpfs/share/skynet/apps/anaconda3/etc/profile.d/conda.sh
conda activate /gpfs/scratch/bz957/brats_skynet
###conda activate powerai1.6_env
cd /gpfs/scratch/bz957/skull_stripping

python -u test.py config/test_all_class.txt
